=== LeeJunung/XmlProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/EISAN/WEB-INF/classes/system/config/Config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="config" type="configType" />

	<xs:complexType name="configType">
		<xs:sequence>
			<xs:element name="env" type="envType" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="envType">
		<xs:sequence>
			<xs:element name="dbType" type="xs:string" />
			<xs:element name="dbHost" type="xs:string" />
			<xs:element name="dbName" type="xs:string" />
			<xs:element name="dbUser" type="xs:string" />
			<xs:element name="dbPass" type="xs:string" />
			<xs:element name="sessionMin" type="xs:decimal" minOccurs="0" />
			<xs:element name="transactionMin" type="xs:decimal" />
			<xs:element name="ajaxMin" type="xs:decimal" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== LeeJunung/XmlProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/EISAN/WEB-INF/classes/eisan/Config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../system/config/Config.xsd">
	<!-- <env> -->
	<!-- <dbType>mysql</dbType> -->
	<!-- <dbHost>192.168.1.200:3333</dbHost> -->
	<!-- <dbName>we</dbName> -->
	<!-- <dbUser>we</dbUser> -->
	<!-- <dbPass>we$2015</dbPass> -->
	<!-- <sessionMin>15</sessionMin> -->
	<!-- <transactionMin>15</transactionMin> -->
	<!-- <ajaxMin>15</ajaxMin> -->
	<!-- </env> -->
	<!-- <env> -->
	<!-- <dbType>oracle</dbType> -->
	<!-- <dbHost>192.168.1.192:1521:XE</dbHost> -->
	<!-- <dbName>WE</dbName> -->
	<!-- <dbUser>we</dbUser> -->
	<!-- <dbPass>we$2014</dbPass> -->
	<!-- <sessionMin>15</sessionMin> -->
	<!-- </env> -->
	<env>
		<dbType>sqlserver</dbType>
		<dbHost>192.168.1.200\EISAN:64555</dbHost>
		<dbName>EISAN</dbName>
		<dbUser>eisan</dbUser>
		<dbPass>eisan$2016</dbPass>
		<sessionMin>15</sessionMin>
		<transactionMin>1</transactionMin>
		<ajaxMin>1</ajaxMin>
	</env>
</config>
